# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      # - image: circleci/golang:1.8
      - image: golang:latest
        environment:
          REVIEWDOG_VERSION: "0.9.11"
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/Ando-O7/circleci-sample
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      # - run: go vet ./... | reviewdog -f=govet -diff="git diff master"
      # - run: go get -v -t -d ./...
      # - run: go test -v ./...
      # - run: curl -fSL https://github.com/reviewdog/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - run: go get -u github.com/reviewdog/reviewdog/cmd/reviewdog
      - run: go vet ./... 2>&1 | reviewdog -f=govet -reporter=github-pr-check # -diff="git diff master"